# Generated by Django 5.1.5 on 2025-02-11 20:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0002_project_url_alter_project_date_alter_project_image_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='project',
            name='category',
            field=models.CharField(default=2024, max_length=100),
            preserve_default=False,
        ),
    ]
